### ISSUE TITLE
help 

### ISSUE THREAD

**Issue by hazed59** [vinanrra/AlbionOnline-RegisterBot#1]
hey man was wondering if you could help me set this up my discord is hazed420#9980

**Comment by vinanrra** [comment]
Here you can invite the public bot I just created:

https://discord.com/oauth2/authorize?client_id=706267055015591976&scope=bot&permissions=2617338880

**Comment by vinanrra** [comment]
> 
> 
> hey man was wondering if you could help me set this up my discord is hazed420#9980

I will try to create a small guide for first steps
